sco_unpack: Don't crash when an SCO file has version 4 but ends before the AI mesh section. I don't know if the game is happy with this in the same way the terrain section is optional, but we better try to unpack as much of the file as we can by adding some leeway. Fixes this problem with an v4 zendar_merchant created by the repacker when converting from v3 to v4 without adding AI meshes:
-- processing scn_azendar_merchant.sco (1/4)

** 1) unpack
Traceback (most recent call last):
  File "C:\PROGRA~2\MOUNT&~1\Modules\NATIVE~1\SCENEO~2\mab_sco_unpack.py", line 359, in <module>
  File "C:\PROGRA~2\MOUNT&~1\Modules\NATIVE~1\SCENEO~2\mab_sco_unpack.py", line 106, in sco_unpack
struct.error: unpack requires a buffer of 4 bytes
[i] unpacking ½scn_azendar_merchant.sco╗ into
              ½_tmp_unpack_folder╗
[>] unpacking 75 mission objects into a JSON file